[package]
name = "rusty-clock-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
paste = "1.0.15"
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", features = ["full"] }

[dev-dependencies]
rstest = "0.26.1"
